""" 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
 """

def findTheDifference(s,t):
    s = list(s)
    t = list(t)
    for i in s:
        t.remove(i)
    return "".join(t)
    

s = "a"
t = "aa"
print(findTheDifference(s, t))